/**
 * PDF Generation Service
 * Generate professional audit reports and working papers in PDF format
 */

import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';

class PDFGenerationService {
  constructor() {
    this.outputDir = './generated-reports';
    this.ensureOutputDir();
  }

  ensureOutputDir() {
    if (!fs.existsSync(this.outputDir)) {
      fs.mkdirSync(this.outputDir, { recursive: true });
    }
  }

  /**
   * Generate audit report PDF
   */
  async generateAuditReport(auditData) {
    const doc = new PDFDocument();
    const filename = `audit-${auditData.auditId}-${Date.now()}.pdf`;
    const filepath = path.join(this.outputDir, filename);

    const stream = fs.createWriteStream(filepath);
    doc.pipe(stream);

    // Header
    doc
      .fontSize(24)
      .font('Helvetica-Bold')
      .text('AUDIT REPORT', { align: 'center' })
      .moveDown(0.5);

    doc
      .fontSize(14)
      .font('Helvetica')
      .text(auditData.auditName, { align: 'center' })
      .moveDown(1);

    // Executive Summary
    doc
      .fontSize(14)
      .font('Helvetica-Bold')
      .text('Executive Summary')
      .moveDown(0.5);

    doc
      .fontSize(11)
      .font('Helvetica')
      .text(auditData.summary || 'No summary provided', { align: 'left' })
      .moveDown(1);

    // Key Findings
    if (auditData.findings && auditData.findings.length > 0) {
      doc
        .fontSize(14)
        .font('Helvetica-Bold')
        .text('Key Findings')
        .moveDown(0.5);

      for (const finding of auditData.findings) {
        doc
          .fontSize(12)
          .font('Helvetica-Bold')
          .text(`${finding.title} (${finding.severity.toUpperCase()})`, {
            color: this.getSeverityColor(finding.severity),
          })
          .moveDown(0.3);

        doc
          .fontSize(10)
          .font('Helvetica')
          .text(finding.description)
          .moveDown(0.2);

        doc
          .fontSize(10)
          .font('Helvetica-Bold')
          .text('Recommendation:')
          .font('Helvetica')
          .text(finding.recommendation)
          .moveDown(0.5);
      }
    }

    // Statistics
    doc
      .addPage()
      .fontSize(14)
      .font('Helvetica-Bold')
      .text('Statistics')
      .moveDown(0.5);

    const stats = [
      ['Total Findings', (auditData.findings || []).length.toString()],
      ['Critical', (auditData.criticalCount || 0).toString()],
      ['Medium', (auditData.mediumCount || 0).toString()],
      ['Low', (auditData.lowCount || 0).toString()],
      ['Status', auditData.status || 'pending'],
    ];

    for (const [label, value] of stats) {
      doc
        .fontSize(11)
        .font('Helvetica-Bold')
        .text(label + ':')
        .moveDown(0.2);
      doc
        .fontSize(11)
        .font('Helvetica')
        .text(value)
        .moveDown(0.3);
    }

    // Footer
    doc
      .fontSize(9)
      .font('Helvetica')
      .text(
        `Generated by Audit Engine | ${new Date().toLocaleString()}`,
        { align: 'center' }
      );

    doc.end();

    return new Promise((resolve, reject) => {
      stream.on('finish', () => {
        console.log(`📄 PDF generated: ${filepath}`);
        resolve({ filepath, filename, url: `/reports/${filename}` });
      });

      stream.on('error', reject);
    });
  }

  /**
   * Generate working papers PDF
   */
  async generateWorkingPapers(workingPaper) {
    const doc = new PDFDocument();
    const filename = `working-papers-${workingPaper.id}-${Date.now()}.pdf`;
    const filepath = path.join(this.outputDir, filename);

    const stream = fs.createWriteStream(filepath);
    doc.pipe(stream);

    // Header
    doc
      .fontSize(20)
      .font('Helvetica-Bold')
      .text('WORKING PAPERS', { align: 'center' })
      .moveDown(1);

    doc
      .fontSize(12)
      .font('Helvetica')
      .text(`Procedure: ${workingPaper.procedureName}`)
      .text(`Date: ${new Date().toLocaleDateString()}`)
      .text(`Prepared by: ${workingPaper.preparedBy || 'N/A'}`)
      .moveDown(1);

    // Procedure Details
    doc
      .fontSize(12)
      .font('Helvetica-Bold')
      .text('Procedure Details')
      .moveDown(0.5);

    doc
      .fontSize(10)
      .font('Helvetica')
      .text(workingPaper.procedureDescription || 'No description provided')
      .moveDown(1);

    // Evidence
    if (workingPaper.evidence && workingPaper.evidence.length > 0) {
      doc
        .fontSize(12)
        .font('Helvetica-Bold')
        .text('Supporting Evidence')
        .moveDown(0.5);

      for (const item of workingPaper.evidence) {
        doc
          .fontSize(10)
          .font('Helvetica')
          .text(`• ${item}`)
          .moveDown(0.2);
      }
    }

    // Conclusion
    doc
      .addPage()
      .fontSize(12)
      .font('Helvetica-Bold')
      .text('Conclusion')
      .moveDown(0.5);

    doc
      .fontSize(10)
      .font('Helvetica')
      .text(workingPaper.conclusion || 'Procedure completed successfully')
      .moveDown(1);

    // Sign-off
    doc
      .fontSize(10)
      .font('Helvetica')
      .text('Reviewed by: ________________')
      .moveDown(0.5)
      .text('Date: ________________');

    doc.end();

    return new Promise((resolve, reject) => {
      stream.on('finish', () => {
        console.log(`📄 Working papers PDF generated: ${filepath}`);
        resolve({ filepath, filename, url: `/reports/${filename}` });
      });

      stream.on('error', reject);
    });
  }

  /**
   * Generate compliance report
   */
  async generateComplianceReport(complianceData) {
    const doc = new PDFDocument();
    const filename = `compliance-${complianceData.auditId}-${Date.now()}.pdf`;
    const filepath = path.join(this.outputDir, filename);

    const stream = fs.createWriteStream(filepath);
    doc.pipe(stream);

    // Header
    doc
      .fontSize(20)
      .font('Helvetica-Bold')
      .text('COMPLIANCE REPORT', { align: 'center' })
      .moveDown(0.5);

    doc
      .fontSize(12)
      .font('Helvetica')
      .text(`Framework: ${complianceData.framework}`, { align: 'center' })
      .moveDown(1);

    // Framework Overview
    doc
      .fontSize(12)
      .font('Helvetica-Bold')
      .text('Framework Overview')
      .moveDown(0.5);

    doc
      .fontSize(10)
      .font('Helvetica')
      .text(
        `This audit assesses compliance with ${complianceData.framework} standards.`
      )
      .moveDown(1);

    // Compliance Checklist
    if (complianceData.checklist && complianceData.checklist.length > 0) {
      doc
        .fontSize(12)
        .font('Helvetica-Bold')
        .text('Compliance Checklist')
        .moveDown(0.5);

      for (const item of complianceData.checklist) {
        const checkmark = item.completed ? '✓' : '✗';
        doc
          .fontSize(10)
          .font('Helvetica')
          .text(`${checkmark} ${item.item}`)
          .moveDown(0.2);
      }
    }

    // Gaps and Recommendations
    if (complianceData.gaps && complianceData.gaps.length > 0) {
      doc
        .addPage()
        .fontSize(12)
        .font('Helvetica-Bold')
        .text('Identified Gaps')
        .moveDown(0.5);

      for (const gap of complianceData.gaps) {
        doc
          .fontSize(10)
          .font('Helvetica-Bold')
          .text(gap.title)
          .moveDown(0.2);
        doc
          .fontSize(10)
          .font('Helvetica')
          .text(gap.recommendation)
          .moveDown(0.3);
      }
    }

    doc.end();

    return new Promise((resolve, reject) => {
      stream.on('finish', () => {
        console.log(`📄 Compliance report PDF generated: ${filepath}`);
        resolve({ filepath, filename, url: `/reports/${filename}` });
      });

      stream.on('error', reject);
    });
  }

  /**
   * Get severity color
   */
  getSeverityColor(severity) {
    switch (severity) {
      case 'critical':
      case 'high':
        return '#FF0000';
      case 'medium':
        return '#FFA500';
      case 'low':
        return '#00AA00';
      default:
        return '#000000';
    }
  }

  /**
   * List generated reports
   */
  listReports() {
    if (!fs.existsSync(this.outputDir)) {
      return [];
    }

    const files = fs.readdirSync(this.outputDir);
    return files.map((file) => ({
      filename: file,
      path: path.join(this.outputDir, file),
      size: fs.statSync(path.join(this.outputDir, file)).size,
      created: fs.statSync(path.join(this.outputDir, file)).birthtime,
    }));
  }

  /**
   * Clean up old reports (older than days)
   */
  cleanupOldReports(days = 30) {
    const cutoffTime = Date.now() - days * 24 * 60 * 60 * 1000;

    const files = this.listReports();
    let cleaned = 0;

    for (const file of files) {
      if (file.created.getTime() < cutoffTime) {
        fs.unlinkSync(file.path);
        cleaned++;
        console.log(`🗑️  Deleted old report: ${file.filename}`);
      }
    }

    return cleaned;
  }
}

export default new PDFGenerationService();
