/**
 * GitHub Connector
 * Auto-create PRs, issues, and manage releases based on audit findings
 */

import { Octokit } from "@octokit/rest";

class GitHubConnector {
  constructor() {
    this.octokit = new Octokit({
      auth: process.env.GITHUB_TOKEN,
    });

    this.owner = process.env.GITHUB_REPO_OWNER || "buledidk";
    this.repo = process.env.GITHUB_REPO_NAME || "Audit-Engine";
    this.defaultBranch = process.env.GITHUB_BRANCH || "main";
    this.isConnected = false;

    this.initialize();
  }

  /**
   * Initialize GitHub connection
   */
  async initialize() {
    try {
      // Verify authentication
      await this.octokit.rest.repos.get({
        owner: this.owner,
        repo: this.repo,
      });

      this.isConnected = true;
      console.log(
        `✅ GitHub connector initialized: ${this.owner}/${this.repo}`
      );
    } catch (error) {
      console.error("❌ Failed to initialize GitHub connector:", error);
      this.isConnected = false;
    }
  }

  /**
   * Create GitHub issue from finding
   */
  async createIssueFromFinding(finding) {
    if (!this.isConnected) {
      console.warn("⚠️  GitHub not connected");
      return null;
    }

    const severityLabel =
      finding.severity === "high"
        ? "critical"
        : finding.severity === "medium"
          ? "bug"
          : "enhancement";

    const body = `
## Finding Details

**Agent:** ${finding.agentName}
**Severity:** ${finding.severity}
**Category:** ${finding.category}
**Confidence:** ${finding.confidence}%

### Description
${finding.description}

### Affected Code
\`\`\`
${finding.affectedCode || "N/A"}
\`\`\`

### Recommended Action
${finding.recommendation || "See description"}

### Action Items
${finding.actionItems ? finding.actionItems.map((item) => `- [ ] ${item}`).join("\n") : "- [ ] Review and remediate"}

---
*Audit ID:* ${finding.auditId}
*Generated by:* Audit Engine
*Date:* ${new Date().toISOString()}
    `;

    try {
      const response = await this.octokit.rest.issues.create({
        owner: this.owner,
        repo: this.repo,
        title: `[${finding.severity.toUpperCase()}] ${finding.title}`,
        body: body,
        labels: [severityLabel, "audit-finding", finding.category],
        assignees:
          finding.assignee ?
            [finding.assignee]
            : [],
      });

      console.log(
        `📤 GitHub issue created: #${response.data.number}`
      );
      return response.data;
    } catch (error) {
      console.error("❌ Failed to create GitHub issue:", error);
      return null;
    }
  }

  /**
   * Create PR from audit report
   */
  async createPRFromAuditReport(report) {
    if (!this.isConnected) return null;

    const timestamp = new Date().toISOString();
    const branchName = `audit/report-${timestamp
      .replace(/[:.]/g, "-")
      .slice(0, 19)}`;

    try {
      // Get current main branch SHA
      const mainRef = await this.octokit.rest.git.getRef({
        owner: this.owner,
        repo: this.repo,
        ref: `heads/${this.defaultBranch}`,
      });

      const baseSha = mainRef.data.object.sha;

      // Create new branch
      await this.octokit.rest.git.createRef({
        owner: this.owner,
        repo: this.repo,
        ref: `refs/heads/${branchName}`,
        sha: baseSha,
      });

      // Create commit with audit report
      const reportContent = Buffer.from(
        this.generateReportMarkdown(report)
      ).toString("base64");

      const filePath = `audit-reports/${report.auditName}-${timestamp
        .slice(0, 10)}.md`;

      const createFileResponse =
        await this.octokit.rest.repos.createOrUpdateFileContents(
          {
            owner: this.owner,
            repo: this.repo,
            path: filePath,
            message: `docs: Add audit report for ${report.auditName}`,
            content: reportContent,
            branch: branchName,
          }
        );

      // Create PR
      const prResponse =
        await this.octokit.rest.pulls.create({
          owner: this.owner,
          repo: this.repo,
          title: `audit: Report for ${report.auditName}`,
          head: branchName,
          base: this.defaultBranch,
          body: this.generatePRDescription(report),
          labels: ["audit-report"],
          draft: false,
        });

      console.log(
        `📤 GitHub PR created: #${prResponse.data.number}`
      );
      return prResponse.data;
    } catch (error) {
      console.error("❌ Failed to create GitHub PR:", error);
      return null;
    }
  }

  /**
   * Add comments to PR with audit findings
   */
  async updatePRWithComments(prNumber, findings) {
    if (!this.isConnected) return false;

    try {
      for (const finding of findings) {
        const comment = `
### 🔍 ${finding.agentName} Finding

**Type:** ${finding.category}
**Severity:** ${finding.severity}
**Confidence:** ${finding.confidence}%

${finding.description}

${finding.recommendation ? `**Recommendation:** ${finding.recommendation}` : ""}
        `;

        await this.octokit.rest.issues.createComment({
          owner: this.owner,
          repo: this.repo,
          issue_number: prNumber,
          body: comment,
        });
      }

      console.log(`📤 PR #${prNumber} updated with ${findings.length} findings`);
      return true;
    } catch (error) {
      console.error("❌ Failed to update PR comments:", error);
      return false;
    }
  }

  /**
   * Create GitHub release
   */
  async createRelease(version, notes) {
    if (!this.isConnected) return null;

    try {
      const response =
        await this.octokit.rest.repos.createRelease({
          owner: this.owner,
          repo: this.repo,
          tag_name: `v${version}`,
          name: `Audit Engine v${version}`,
          body: notes,
          draft: false,
          prerelease: false,
        });

      console.log(
        `📤 GitHub release created: v${version}`
      );
      return response.data;
    } catch (error) {
      console.error("❌ Failed to create GitHub release:", error);
      return null;
    }
  }

  /**
   * Handle GitHub webhook
   */
  async handleWebhook(req, res) {
    const signature = req.headers["x-hub-signature-256"];
    const payload = JSON.stringify(req.body);

    // Verify signature
    const crypto = await import("crypto");
    const hash =
      "sha256=" +
      crypto
        .createHmac(
          "sha256",
          process.env.GITHUB_WEBHOOK_SECRET
        )
        .update(payload)
        .digest("hex");

    if (hash !== signature) {
      console.warn(
        "⚠️  GitHub webhook signature mismatch"
      );
      return res.status(401).send("Unauthorized");
    }

    const event = req.headers["x-github-event"];

    if (event === "push") {
      console.log("📥 GitHub push event received");
      // Handle push events
    } else if (event === "pull_request") {
      console.log("📥 GitHub PR event received");
      // Handle PR events
    } else if (event === "issues") {
      console.log("📥 GitHub issue event received");
      // Handle issue events
    }

    res.status(200).send("OK");
  }

  /**
   * Generate PR description
   */
  generatePRDescription(report) {
    return `
# Audit Report: ${report.auditName}

## Summary
${report.summary || "See attached audit report"}

## Findings
- **Total:** ${report.totalFindings}
- **Critical:** ${report.criticalCount}
- **Medium:** ${report.mediumCount}
- **Low:** ${report.lowCount}

## Status
${report.status === "passed" ? "✅ PASSED" : "❌ FAILED"}

---

*Generated by Audit Engine*
*Date:* ${new Date().toISOString()}
    `;
  }

  /**
   * Generate report markdown
   */
  generateReportMarkdown(report) {
    return `# ${report.auditName} - Audit Report

**Date:** ${new Date().toISOString()}
**Status:** ${report.status}

## Summary
${report.summary}

## Findings

${report.findings
  .map(
    (finding) => `
### ${finding.title}
- **Severity:** ${finding.severity}
- **Category:** ${finding.category}
- **Agent:** ${finding.agentName}

${finding.description}

**Recommendation:** ${finding.recommendation}
`
  )
  .join("\n")}

## Conclusion
${report.conclusion}
    `;
  }

  /**
   * Get connector status
   */
  async getStatus() {
    return {
      name: "GitHub",
      connected: this.isConnected,
      repo: `${this.owner}/${this.repo}`,
      branch: this.defaultBranch,
      lastCheck: new Date(),
    };
  }
}

export default new GitHubConnector();
