// ═══════════════════════════════════════════════════════════════
// DOCX EXPORTER — Real .docx generation via docx package
// AuditEngine v10 AURA
// ═══════════════════════════════════════════════════════════════

async function loadDocx() {
  return import("docx");
}

function downloadBlob(blob, filename) {
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  URL.revokeObjectURL(a.href);
}

function makeFilename(entityName, ref, suffix) {
  return (entityName || "Entity").replace(/[^a-zA-Z0-9]/g, "_") + "_" + ref + "_" + suffix + ".docx";
}

/**
 * Create a branded header/footer paragraph set.
 */
function buildHeaderFooter(docx, firmName) {
  return {
    default: new docx.Header({
      children: [
        new docx.Paragraph({
          children: [
            new docx.TextRun({ text: firmName || "[Firm Name]", bold: true, size: 16, font: "Calibri" }),
            new docx.TextRun({ text: "  |  CONFIDENTIAL", size: 14, color: "999999", font: "Calibri" }),
          ],
          border: { bottom: { color: "1a237e", size: 6, style: docx.BorderStyle.SINGLE, space: 4 } },
        }),
      ],
    }),
    defaultFooter: new docx.Footer({
      children: [
        new docx.Paragraph({
          children: [
            new docx.TextRun({ text: "Generated by AuditEngine v10 AURA | " + new Date().toISOString().slice(0, 10), size: 14, color: "999999", font: "Calibri" }),
          ],
          alignment: docx.AlignmentType.CENTER,
          border: { top: { color: "cccccc", size: 3, style: docx.BorderStyle.SINGLE, space: 4 } },
        }),
      ],
    }),
  };
}

function heading(docx, text, level) {
  return new docx.Paragraph({
    children: [new docx.TextRun({ text, bold: true, size: level === 1 ? 36 : level === 2 ? 28 : 24, font: "Calibri", color: level === 1 ? "1a237e" : "283593" })],
    spacing: { before: level === 1 ? 400 : 300, after: 150 },
  });
}

function para(docx, text, opts = {}) {
  return new docx.Paragraph({
    children: [new docx.TextRun({ text, size: 22, font: "Calibri", ...opts })],
    spacing: { after: 120 },
  });
}

function bulletPara(docx, text) {
  return new docx.Paragraph({
    children: [new docx.TextRun({ text, size: 22, font: "Calibri" })],
    bullet: { level: 0 },
    spacing: { after: 60 },
  });
}

function simpleTable(docx, headers, rows) {
  return new docx.Table({
    width: { size: 100, type: docx.WidthType.PERCENTAGE },
    rows: [
      new docx.TableRow({
        tableHeader: true,
        children: headers.map(h => new docx.TableCell({
          children: [new docx.Paragraph({ children: [new docx.TextRun({ text: h, bold: true, size: 20, font: "Calibri" })] })],
          shading: { fill: "e8eaf6" },
          verticalAlign: docx.VerticalAlign.CENTER,
        })),
      }),
      ...rows.map(row => new docx.TableRow({
        children: row.map(cell => new docx.TableCell({
          children: [new docx.Paragraph({ children: [new docx.TextRun({ text: String(cell || ""), size: 20, font: "Calibri" })] })],
          verticalAlign: docx.VerticalAlign.CENTER,
        })),
      })),
    ],
  });
}

// ═══ DOCUMENT GENERATORS ═══

/**
 * A1: Engagement Letter (ISA 210)
 */
export async function generateEngagementLetter(ctx, engagementLetterData) {
  const docx = await loadDocx();
  const el = engagementLetterData;
  const rep = s => s.replace(/\{FYE\}/g, ctx.fye || "[FYE]").replace(/\{FRAMEWORK\}/g, ctx.framework || "[Framework]");
  const hf = buildHeaderFooter(docx, ctx.firmName);

  const children = [
    heading(docx, "ENGAGEMENT LETTER", 1),
    para(docx, ctx.firmName || "[Firm Name]", { bold: true }),
    para(docx, ""),
    para(docx, "To: The Board of Directors of " + (ctx.entityName || "[Entity]"), { bold: true }),
    para(docx, "Date: " + new Date().toISOString().slice(0, 10)),
    para(docx, "Re: Audit of financial statements for the year ended " + (ctx.fye || "[FYE]")),

    heading(docx, "1. Objective (ISA 200.11)", 2),
    para(docx, rep(el.objective)),

    heading(docx, "2. Scope of Audit", 2),
    ...el.scope.map(s => bulletPara(docx, rep(s))),

    heading(docx, "3. Engagement Team", 2),
    simpleTable(docx, ["Role", "Name"], [
      ["Engagement Partner", ctx.partner || "[TBD]"],
      ["Audit Manager", ctx.manager || "[TBD]"],
      ["Audit Firm", ctx.firmName || "[TBD]"],
    ]),

    heading(docx, "4. Responsibilities of Management (ISA 210.6)", 2),
    simpleTable(docx, ["#", "Responsibility"],
      el.responsibilities_management.map((r, i) => [String(i + 1), r])
    ),

    heading(docx, "5. Responsibilities of the Auditor (ISA 210.10)", 2),
    simpleTable(docx, ["#", "Responsibility"],
      el.responsibilities_auditor.map((r, i) => [String(i + 1), r])
    ),

    heading(docx, "6. Inherent Limitations (ISA 200.A53)", 2),
    para(docx, el.limitations || ""),

    heading(docx, "7. Fees", 2),
    para(docx, "[To be agreed]"),
    para(docx, ""),
    para(docx, "Please sign and return one copy of this letter to indicate your acknowledgement of, and agreement with, the arrangements for our audit."),
    para(docx, ""),
    para(docx, "For and on behalf of " + (ctx.firmName || "[Firm]")),
    para(docx, "____________________________"),
    para(docx, ctx.partner || "[Partner]"),
    para(docx, ""),
    para(docx, "For and on behalf of " + (ctx.entityName || "[Entity]")),
    para(docx, "____________________________"),
    para(docx, "[Director Name]"),
  ];

  const doc = new docx.Document({
    sections: [{
      headers: { default: hf.default },
      footers: { default: hf.defaultFooter },
      children,
    }],
  });

  const blob = await docx.Packer.toBlob(doc);
  downloadBlob(blob, makeFilename(ctx.entityName, "A1", "Engagement_Letter"));
}

/**
 * E4: Written Representations (ISA 580)
 */
export async function generateRepresentationsLetter(ctx, representationsData) {
  const docx = await loadDocx();
  const reps = representationsData;
  const rep = s => s.replace(/\{FRAMEWORK\}/g, ctx.framework || "[Framework]");
  const hf = buildHeaderFooter(docx, ctx.firmName);

  const children = [
    heading(docx, "WRITTEN REPRESENTATIONS", 1),
    para(docx, "ISA 580", { color: "666666" }),
    para(docx, ""),
    para(docx, "Dear " + (ctx.firmName || "[Firm Name]") + ","),
    para(docx, "This representation letter is provided in connection with your audit of the financial statements of " + (ctx.entityName || "[Entity]") + " for the year ended " + (ctx.fye || "[FYE]") + "."),
    para(docx, ""),
    simpleTable(docx, ["Ref", "Representation", "ISA", "Mandatory"],
      reps.map(r => [r.ref, rep(r.text), r.isa, r.mandatory ? "YES" : "No"])
    ),
    para(docx, ""),
    para(docx, "Yours faithfully,"),
    para(docx, ""),
    para(docx, "____________________________"),
    para(docx, "Director"),
    para(docx, ctx.entityName || "[Entity]"),
    para(docx, "Date: _______________"),
  ];

  const doc = new docx.Document({
    sections: [{ headers: { default: hf.default }, footers: { default: hf.defaultFooter }, children }],
  });

  const blob = await docx.Packer.toBlob(doc);
  downloadBlob(blob, makeFilename(ctx.entityName, "E4", "Representations"));
}

/**
 * F1: Management Letter (ISA 265)
 */
export async function generateManagementLetter(ctx) {
  const docx = await loadDocx();
  const hf = buildHeaderFooter(docx, ctx.firmName);

  const children = [
    heading(docx, "MANAGEMENT LETTER", 1),
    para(docx, "ISA 265 — Communicating Deficiencies in Internal Control", { color: "666666" }),
    para(docx, ""),
    para(docx, "PRIVATE AND CONFIDENTIAL", { bold: true }),
    para(docx, ""),
    para(docx, "The Board of Directors"),
    para(docx, ctx.entityName || "[Entity]"),
    para(docx, ""),
    para(docx, "Dear Directors,"),
    para(docx, "Following our audit of the financial statements for the year ended " + (ctx.fye || "[FYE]") + ", we write to bring the following matters to your attention in accordance with ISA (UK) 265."),

    heading(docx, "Matters Arising", 2),
    simpleTable(docx, ["#", "Finding", "Risk/Impact", "Recommendation", "Priority", "Management Response"], [
      ["1", "", "", "", "", ""],
      ["2", "", "", "", "", ""],
      ["3", "", "", "", "", ""],
    ]),

    heading(docx, "Status of Prior Year Matters", 2),
    simpleTable(docx, ["#", "Prior Year Finding", "Status", "Comment"], [
      ["1", "", "", ""],
    ]),

    para(docx, ""),
    para(docx, "This letter is provided for the sole use of the directors of " + (ctx.entityName || "[Entity]") + " and should not be disclosed to third parties without our prior written consent."),
    para(docx, ""),
    para(docx, "Yours faithfully,"),
    para(docx, ""),
    para(docx, "____________________________"),
    para(docx, ctx.firmName || "[Firm]"),
    para(docx, ctx.partner || "[Partner]"),
  ];

  const doc = new docx.Document({
    sections: [{ headers: { default: hf.default }, footers: { default: hf.defaultFooter }, children }],
  });

  const blob = await docx.Packer.toBlob(doc);
  downloadBlob(blob, makeFilename(ctx.entityName, "F1", "Management_Letter"));
}

/**
 * F2: Audit Report (ISA 700)
 */
export async function generateAuditReport(ctx, auditOpinions) {
  const docx = await loadDocx();
  const ops = auditOpinions;
  const rep = s => s.replace(/\{FYE\}/g, ctx.fye || "[FYE]").replace(/\{FRAMEWORK\}/g, ctx.framework || "[Framework]");
  const hf = buildHeaderFooter(docx, ctx.firmName);

  const children = [
    heading(docx, "INDEPENDENT AUDITOR'S REPORT", 1),
    para(docx, "To the members of " + (ctx.entityName || "[Entity]")),

    heading(docx, "Opinion", 2),
    para(docx, "We have audited the financial statements of " + (ctx.entityName || "[Entity]") + " for the year ended " + (ctx.fye || "[FYE]") + " which comprise the statement of comprehensive income, the balance sheet, the statement of changes in equity, the statement of cash flows, and related notes to the financial statements, including a summary of significant accounting policies."),
    para(docx, rep(ops.unmodified.wording)),

    heading(docx, "Basis for Opinion", 2),
    para(docx, "We conducted our audit in accordance with International Standards on Auditing (UK) (ISAs (UK)) and applicable law. Our responsibilities under those standards are further described in the Auditor's responsibilities for the audit of the financial statements section of our report. We are independent of the company in accordance with the ethical requirements that are relevant to our audit of the financial statements in the UK, including the FRC's Ethical Standard, and we have fulfilled our other ethical responsibilities in accordance with these requirements. We believe that the audit evidence we have obtained is sufficient and appropriate to provide a basis for our opinion."),

    heading(docx, "Conclusions Relating to Going Concern", 2),
    para(docx, "In auditing the financial statements, we have concluded that the directors' use of the going concern basis of accounting in the preparation of the financial statements is appropriate."),
    para(docx, "Based on the work we have performed, we have not identified any material uncertainties relating to events or conditions that, individually or collectively, may cast significant doubt on the company's ability to continue as a going concern for a period of at least twelve months from when the financial statements are authorised for issue."),

    heading(docx, "Other Information", 2),
    para(docx, "The directors are responsible for the other information. The other information comprises the information included in the annual report, other than the financial statements and our auditor's report thereon. Our opinion on the financial statements does not cover the other information and we do not express any form of assurance conclusion thereon."),

    heading(docx, "Responsibilities of Directors", 2),
    para(docx, "As explained more fully in the directors' responsibilities statement, the directors are responsible for the preparation of the financial statements and for being satisfied that they give a true and fair view, and for such internal control as the directors determine is necessary to enable the preparation of financial statements that are free from material misstatement, whether due to fraud or error."),

    heading(docx, "Auditor's Responsibilities", 2),
    para(docx, "Our objectives are to obtain reasonable assurance about whether the financial statements as a whole are free from material misstatement, whether due to fraud or error, and to issue an auditor's report that includes our opinion. Reasonable assurance is a high level of assurance, but is not a guarantee that an audit conducted in accordance with ISAs (UK) will always detect a material misstatement when it exists."),

    para(docx, ""),
    para(docx, ctx.firmName || "[Firm Name]", { bold: true }),
    para(docx, "Statutory Auditor"),
    para(docx, "[Address]"),
    para(docx, "Date: _______________"),
  ];

  const doc = new docx.Document({
    sections: [{ headers: { default: hf.default }, footers: { default: hf.defaultFooter }, children }],
  });

  const blob = await docx.Packer.toBlob(doc);
  downloadBlob(blob, makeFilename(ctx.entityName, "F2", "Audit_Report"));
}

/**
 * Planning Memo — compiles A1-A10, B1-B3 into a single document.
 */
export async function generatePlanningMemo(ctx) {
  const docx = await loadDocx();
  const hf = buildHeaderFooter(docx, ctx.firmName);

  const children = [
    heading(docx, "AUDIT PLANNING MEMORANDUM", 1),
    para(docx, ctx.entityName || "[Entity]", { bold: true, size: 28 }),
    para(docx, "Year ended " + (ctx.fye || "[FYE]")),
    para(docx, ""),

    heading(docx, "1. Engagement Details", 2),
    simpleTable(docx, ["Field", "Detail"], [
      ["Entity", ctx.entityName || ""],
      ["FYE", ctx.fye || ""],
      ["Industry", ctx.industry || ""],
      ["Sector", ctx.sector || ""],
      ["Framework", ctx.framework || ""],
      ["Entity Size", ctx.entitySize || ""],
      ["Engagement Partner", ctx.partner || ""],
      ["Audit Manager", ctx.manager || ""],
      ["Materiality", "£" + (ctx.materiality || "TBD")],
      ["Performance Materiality", "£" + (ctx.perfMateriality || "TBD")],
      ["Trivial Threshold", "£" + (ctx.trivial || "TBD")],
    ]),

    heading(docx, "2. Audit Strategy (ISA 300)", 2),
    para(docx, ctx.wpNotes?.a3 || "[Refer to A3 working paper]"),

    heading(docx, "3. Understanding the Entity (ISA 315)", 2),
    para(docx, ctx.wpNotes?.a5 || "[Refer to A5 working paper]"),

    heading(docx, "4. Fraud Risk Assessment (ISA 240)", 2),
    para(docx, ctx.wpNotes?.a6 || "[Refer to A6 working paper]"),

    heading(docx, "5. Risk Assessment Summary", 2),
    para(docx, ctx.wpNotes?.b1 || "[Refer to B1 working paper]"),

    heading(docx, "6. Identified Risks", 2),
  ];

  if (ctx.risks && ctx.risks.length) {
    children.push(simpleTable(docx, ["Ref", "Risk", "Level", "ISA"],
      ctx.risks.map(r => [r.id, r.t, r.lv, r.isa])
    ));
  }

  children.push(
    heading(docx, "7. Materiality (ISA 320)", 2),
    para(docx, ctx.wpNotes?.a4 || "[Refer to A4 working paper]"),
    heading(docx, "8. Analytical Review (ISA 520)", 2),
    para(docx, ctx.wpNotes?.a8 || "[Refer to A8 working paper]"),
    para(docx, ""),
    para(docx, "Prepared by: " + (ctx.partner || "[Partner]")),
    para(docx, "Date: " + new Date().toISOString().slice(0, 10)),
  );

  const doc = new docx.Document({
    sections: [{ headers: { default: hf.default }, footers: { default: hf.defaultFooter }, children }],
  });

  const blob = await docx.Packer.toBlob(doc);
  downloadBlob(blob, makeFilename(ctx.entityName, "PLAN", "Planning_Memo"));
}

/**
 * Completion Memo — compiles E1-E6, A7 into a single document.
 */
export async function generateCompletionMemo(ctx) {
  const docx = await loadDocx();
  const hf = buildHeaderFooter(docx, ctx.firmName);

  const children = [
    heading(docx, "AUDIT COMPLETION MEMORANDUM", 1),
    para(docx, ctx.entityName || "[Entity]", { bold: true, size: 28 }),
    para(docx, "Year ended " + (ctx.fye || "[FYE]")),
    para(docx, ""),

    heading(docx, "1. Summary of Audit Work", 2),
    para(docx, ctx.wpNotes?.e6 || "[Refer to E6 working paper]"),

    heading(docx, "2. Going Concern (ISA 570)", 2),
    para(docx, ctx.wpNotes?.a7 || "[Refer to A7 working paper]"),
    para(docx, "Going concern conclusion: " + (ctx.wpNotes?.a7_overall_conclusion || "[Not documented]")),
    para(docx, "Going concern basis appropriate: " + (ctx.wpNotes?.a7_gc_appropriate || "[Not assessed]")),

    heading(docx, "3. Subsequent Events (ISA 560)", 2),
    para(docx, ctx.wpNotes?.e3 || "[Refer to E3 working paper]"),

    heading(docx, "4. Summary of Misstatements (ISA 450)", 2),
    para(docx, ctx.wpNotes?.e5 || "[Refer to E5 working paper]"),

    heading(docx, "5. Significant Matters", 2),
    para(docx, ctx.wpNotes?.e6_matters || "[No significant matters documented]"),

    heading(docx, "6. Proposed Opinion", 2),
    para(docx, ctx.wpNotes?.e6_opinion || "[Not yet determined]"),

    heading(docx, "7. Final Analytical Review (ISA 520.6)", 2),
    para(docx, ctx.wpNotes?.e2 || "[Refer to E2 working paper]"),

    para(docx, ""),
    para(docx, "Engagement Partner: " + (ctx.partner || "[Partner]")),
    para(docx, "Date: " + new Date().toISOString().slice(0, 10)),
  ];

  const doc = new docx.Document({
    sections: [{ headers: { default: hf.default }, footers: { default: hf.defaultFooter }, children }],
  });

  const blob = await docx.Packer.toBlob(doc);
  downloadBlob(blob, makeFilename(ctx.entityName, "COMP", "Completion_Memo"));
}
