// ═══════════════════════════════════════════════════════════════
// WORD GENERATOR — Professional .docx document generation
// AuditEngine v10 AURA
// Uses docx library: Calibri body, Cambria headings, firm header/footer
// ═══════════════════════════════════════════════════════════════

async function loadDocx() { return import("docx"); }

function dlBlob(blob, filename) {
  const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = filename; a.click(); URL.revokeObjectURL(a.href);
}

function mkName(ctx, ref, suffix) {
  return (ctx.entityName || "Entity").replace(/[^a-zA-Z0-9]/g, "_") + "_" + (ctx.fye || "FYE").replace(/[^a-zA-Z0-9]/g, "") + "_" + ref + "_" + new Date().toISOString().slice(0, 10) + "_" + suffix + ".docx";
}

function mkHeader(docx, ctx) {
  return new docx.Header({ children: [new docx.Paragraph({ children: [new docx.TextRun({ text: ctx.firmName || "[Firm Name]", bold: true, size: 18, font: "Cambria" }), new docx.TextRun({ text: "  |  CONFIDENTIAL", size: 16, color: "999999", font: "Calibri" })], border: { bottom: { color: "1a237e", size: 6, style: docx.BorderStyle.SINGLE, space: 4 } } })] });
}

function mkFooter(docx, ctx) {
  return new docx.Footer({ children: [new docx.Paragraph({ children: [new docx.TextRun({ text: (ctx.entityName || "") + " | " + (ctx.fye || "") + " | Generated by AuditEngine v10 AURA · Indus Nexus Limited · " + new Date().toISOString().slice(0, 10), size: 14, color: "999999", font: "Calibri" })], alignment: docx.AlignmentType.CENTER, border: { top: { color: "cccccc", size: 3, style: docx.BorderStyle.SINGLE, space: 4 } } })] });
}

function h(docx, text, level = 1) {
  return new docx.Paragraph({ children: [new docx.TextRun({ text, bold: true, size: level === 1 ? 36 : level === 2 ? 28 : 24, font: "Cambria", color: level === 1 ? "1a237e" : "283593" })], spacing: { before: level === 1 ? 500 : 300, after: 200 } });
}

function p(docx, text, opts = {}) {
  return new docx.Paragraph({ children: [new docx.TextRun({ text, size: 22, font: "Calibri", ...opts })], spacing: { after: 120 } });
}

function bullet(docx, text) {
  return new docx.Paragraph({ children: [new docx.TextRun({ text, size: 22, font: "Calibri" })], bullet: { level: 0 }, spacing: { after: 80 } });
}

function tbl(docx, headers, rows) {
  return new docx.Table({ width: { size: 100, type: docx.WidthType.PERCENTAGE }, rows: [
    new docx.TableRow({ tableHeader: true, children: headers.map(hh => new docx.TableCell({ children: [new docx.Paragraph({ children: [new docx.TextRun({ text: hh, bold: true, size: 20, font: "Calibri" })] })], shading: { fill: "e8eaf6" } })) }),
    ...rows.map(row => new docx.TableRow({ children: row.map(cell => new docx.TableCell({ children: [new docx.Paragraph({ children: [new docx.TextRun({ text: String(cell || ""), size: 20, font: "Calibri" })] })] })) }))
  ] });
}

function mkDoc(docx, ctx, children) {
  return new docx.Document({ sections: [{ headers: { default: mkHeader(docx, ctx) }, footers: { default: mkFooter(docx, ctx) }, children }] });
}

// ─── A) ENGAGEMENT LETTER ───
export async function generateEngagementLetterDocx(ctx, engLetter) {
  const docx = await loadDocx();
  const rep = s => (s || "").replace(/\{FYE\}/g, ctx.fye || "[FYE]").replace(/\{FRAMEWORK\}/g, ctx.framework || "[Framework]");
  const ch = [
    h(docx, "ENGAGEMENT LETTER"), p(docx, ctx.firmName || "[Firm Name]", { bold: true }), p(docx, ""),
    p(docx, "To: The Board of Directors of " + (ctx.entityName || "[Entity]"), { bold: true }),
    p(docx, "Date: " + new Date().toISOString().slice(0, 10)),
    p(docx, "Re: Audit of financial statements for the year ended " + (ctx.fye || "[FYE]")),
    h(docx, "1. Objective (ISA 200.11)", 2), p(docx, rep(engLetter.objective)),
    h(docx, "2. Scope of Audit", 2), ...engLetter.scope.map(s => bullet(docx, rep(s))),
    h(docx, "3. Engagement Team", 2),
    tbl(docx, ["Role", "Name"], [["Engagement Partner", ctx.partner || "[TBD]"], ["Audit Manager", ctx.manager || "[TBD]"], ["Audit Firm", ctx.firmName || "[TBD]"]]),
    h(docx, "4. Responsibilities of Management (ISA 210.6)", 2),
    tbl(docx, ["#", "Responsibility"], engLetter.responsibilities_management.map((r, i) => [String(i + 1), r])),
    h(docx, "5. Responsibilities of the Auditor (ISA 210.10)", 2),
    tbl(docx, ["#", "Responsibility"], engLetter.responsibilities_auditor.map((r, i) => [String(i + 1), r])),
    h(docx, "6. Inherent Limitations (ISA 200.A53)", 2), p(docx, engLetter.limitations || ""),
    h(docx, "7. GDPR Data Processing Notice", 2),
    p(docx, "In the course of our audit, we will process personal data in accordance with the UK General Data Protection Regulation and the Data Protection Act 2018. Details of our privacy policy are available on request."),
    h(docx, "8. Fees", 2), p(docx, "[To be agreed]"),
    h(docx, "9. Governing Law", 2), p(docx, "This engagement letter shall be governed by and construed in accordance with the laws of England and Wales."),
    p(docx, ""), p(docx, "Please sign and return one copy of this letter."),
    p(docx, ""), p(docx, "For and on behalf of " + (ctx.firmName || "[Firm]")), p(docx, "____________________________"), p(docx, ctx.partner || "[Partner]"),
    p(docx, ""), p(docx, "For and on behalf of " + (ctx.entityName || "[Entity]")), p(docx, "____________________________"), p(docx, "[Director Name]   Date: _______________"),
  ];
  const doc = mkDoc(docx, ctx, ch);
  const blob = await docx.Packer.toBlob(doc);
  dlBlob(blob, mkName(ctx, "A1", "Engagement_Letter"));
}

// ─── B) REPRESENTATION LETTER ───
export async function generateRepresentationLetterDocx(ctx, reps) {
  const docx = await loadDocx();
  const rep = s => (s || "").replace(/\{FRAMEWORK\}/g, ctx.framework || "[Framework]");
  const ch = [
    h(docx, "WRITTEN REPRESENTATIONS"), p(docx, "ISA 580", { color: "666666" }), p(docx, ""),
    p(docx, "Dear " + (ctx.firmName || "[Firm Name]") + ","),
    p(docx, "This representation letter is provided in connection with your audit of the financial statements of " + (ctx.entityName || "[Entity]") + " for the year ended " + (ctx.fye || "[FYE]") + "."),
    p(docx, "We confirm, to the best of our knowledge and belief, the following representations:"), p(docx, ""),
    tbl(docx, ["Ref", "Representation", "ISA", "Mandatory"], reps.map(r => [r.ref, rep(r.text), r.isa, r.mandatory ? "YES" : "No"])),
    p(docx, ""), p(docx, "Yours faithfully,"), p(docx, ""), p(docx, "____________________________"),
    p(docx, "Director"), p(docx, ctx.entityName || "[Entity]"), p(docx, "Date: _______________"),
  ];
  const doc = mkDoc(docx, ctx, ch);
  const blob = await docx.Packer.toBlob(doc);
  dlBlob(blob, mkName(ctx, "E4", "Representations"));
}

// ─── C) MANAGEMENT LETTER ───
export async function generateManagementLetterDocx(ctx) {
  const docx = await loadDocx();
  const ch = [
    h(docx, "MANAGEMENT LETTER"), p(docx, "ISA 265 — Communicating Deficiencies in Internal Control", { color: "666666" }),
    p(docx, ""), p(docx, "PRIVATE AND CONFIDENTIAL", { bold: true }),
    p(docx, "The Board of Directors"), p(docx, ctx.entityName || "[Entity]"), p(docx, ""),
    p(docx, "Dear Directors,"),
    p(docx, "Following our audit of the financial statements for the year ended " + (ctx.fye || "[FYE]") + ", we write to bring the following matters to your attention in accordance with ISA (UK) 265."),
    h(docx, "1. Executive Summary", 2),
    p(docx, "[Summary of key findings and their overall significance to the financial statements]"),
    h(docx, "2. Matters Arising", 2),
    tbl(docx, ["Ref", "Finding", "Risk Rating", "Affected Area", "ISA Ref", "Recommendation", "Mgmt Response", "Owner", "Target Date"],
      [["ML01", "", "", "", "", "", "", "", ""], ["ML02", "", "", "", "", "", "", "", ""], ["ML03", "", "", "", "", "", "", "", ""]]),
    h(docx, "3. Status of Prior Year Matters", 2),
    tbl(docx, ["Ref", "Prior Year Finding", "Status", "Comment"], [["PY01", "", "", ""]]),
    h(docx, "Appendix: Risk Categorisation", 2),
    bullet(docx, "High — Matters that could result in material misstatement or significant deficiency in internal control"),
    bullet(docx, "Medium — Matters that could result in more than trivial misstatement or represent a deficiency worth reporting"),
    bullet(docx, "Low — Matters for improvement that represent best practice recommendations"),
    p(docx, ""), p(docx, "This letter is for the sole use of the directors of " + (ctx.entityName || "[Entity]") + "."),
    p(docx, ""), p(docx, "Yours faithfully,"), p(docx, "____________________________"), p(docx, ctx.firmName || "[Firm]"), p(docx, ctx.partner || "[Partner]"),
  ];
  const doc = mkDoc(docx, ctx, ch);
  const blob = await docx.Packer.toBlob(doc);
  dlBlob(blob, mkName(ctx, "F1", "Management_Letter"));
}

// ─── D) AUDIT REPORT (all 7 opinion types) ───
export async function generateAuditReportDocx(ctx, opinions, opinionType = "unmodified") {
  const docx = await loadDocx();
  const rep = s => (s || "").replace(/\{FYE\}/g, ctx.fye || "[FYE]").replace(/\{FRAMEWORK\}/g, ctx.framework || "[Framework]");
  const opinion = opinions[opinionType] || opinions.unmodified;
  const ch = [
    h(docx, "INDEPENDENT AUDITOR'S REPORT"), p(docx, "To the members of " + (ctx.entityName || "[Entity]")),
    h(docx, opinionType === "unmodified" ? "Opinion" : (opinionType === "adverse" ? "Adverse Opinion" : opinionType === "disclaimer" ? "Disclaimer of Opinion" : "Qualified Opinion"), 2),
    p(docx, "We have audited the financial statements of " + (ctx.entityName || "[Entity]") + " for the year ended " + (ctx.fye || "[FYE]") + " which comprise the statement of comprehensive income, the balance sheet, the statement of changes in equity, the statement of cash flows, and related notes."),
    p(docx, rep(opinion.wording)),
    h(docx, "Basis for Opinion", 2),
    p(docx, "We conducted our audit in accordance with International Standards on Auditing (UK) (ISAs (UK)) and applicable law. Our responsibilities under those standards are further described in the Auditor's responsibilities section. We are independent of the company in accordance with the ethical requirements relevant to our audit including the FRC's Ethical Standard."),
    h(docx, "Conclusions Relating to Going Concern (ISA 570)", 2),
    p(docx, "In auditing the financial statements, we have concluded that the directors' use of the going concern basis of accounting in the preparation of the financial statements is appropriate. Based on the work we have performed, we have not identified any material uncertainties relating to events or conditions that may cast significant doubt on the company's ability to continue as a going concern for at least twelve months from when the financial statements are authorised for issue."),
    h(docx, "Other Information (ISA 720)", 2),
    p(docx, "The directors are responsible for the other information. Our opinion does not cover the other information and we do not express any form of assurance conclusion thereon."),
    h(docx, "Responsibilities of Directors and Those Charged with Governance", 2),
    p(docx, "The directors are responsible for the preparation of financial statements that give a true and fair view in accordance with " + (ctx.framework || "[Framework]") + " and the Companies Act 2006, and for such internal control as the directors determine is necessary to enable the preparation of financial statements that are free from material misstatement, whether due to fraud or error."),
    h(docx, "Auditor's Responsibilities for the Audit of the Financial Statements", 2),
    p(docx, "Our objectives are to obtain reasonable assurance about whether the financial statements as a whole are free from material misstatement, whether due to fraud or error, and to issue an auditor's report that includes our opinion. Reasonable assurance is a high level of assurance but is not a guarantee."),
    bullet(docx, "We identify and assess risks of material misstatement (ISA 315)"),
    bullet(docx, "We design and perform audit procedures responsive to those risks (ISA 330)"),
    bullet(docx, "We obtain sufficient appropriate audit evidence (ISA 500)"),
    bullet(docx, "We evaluate the overall presentation of the financial statements (ISA 700)"),
    h(docx, "Report on Other Legal and Regulatory Requirements", 2),
    p(docx, "In our opinion, based on the work undertaken in the course of the audit, the information given in the directors' report for the financial year is consistent with the financial statements and has been prepared in accordance with applicable legal requirements (Companies Act 2006 s.496)."),
    p(docx, ""), p(docx, ctx.firmName || "[Firm Name]", { bold: true }), p(docx, "Statutory Auditor"), p(docx, "[Address]"), p(docx, "Date: _______________"),
  ];
  const doc = mkDoc(docx, ctx, ch);
  const blob = await docx.Packer.toBlob(doc);
  dlBlob(blob, mkName(ctx, "F2", "Audit_Report"));
}

// ─── E) PLANNING MEMO ───
export async function generatePlanningMemoDocx(ctx) {
  const docx = await loadDocx();
  const ch = [
    h(docx, "AUDIT PLANNING MEMORANDUM"), p(docx, ctx.entityName || "[Entity]", { bold: true, size: 28 }),
    p(docx, "Year ended " + (ctx.fye || "[FYE]")), p(docx, ""),
    h(docx, "1. Entity Background and Regulatory Environment", 2),
    tbl(docx, ["Field", "Detail"], [["Entity", ctx.entityName || ""], ["Company Number", ctx.companyNumber || "[TBD]"], ["FYE", ctx.fye || ""], ["Industry", ctx.industry || ""], ["Sector", ctx.sector || ""], ["Framework", ctx.framework || ""], ["Size", ctx.entitySize || ""], ["Partner", ctx.partner || ""], ["Manager", ctx.manager || ""]]),
    h(docx, "2. Prior Year Issues", 2), p(docx, ctx.wpNotes?.priorYear || "[Document prior year issues and their resolution]"),
    h(docx, "3. Changes in Business", 2), p(docx, ctx.wpNotes?.changes || "[Document significant changes: new contracts, personnel, systems, accounting policies]"),
    h(docx, "4. Materiality (ISA 320)", 2),
    tbl(docx, ["Measure", "Amount"], [["Overall Materiality", "£" + (ctx.materiality || "TBD")], ["Performance Materiality", "£" + (ctx.perfMateriality || "TBD")], ["Trivial Threshold", "£" + (ctx.trivial || "TBD")]]),
    h(docx, "5. Risk Assessment Summary (ISA 315)", 2), p(docx, ctx.wpNotes?.b1 || "[Refer to B1]"),
    h(docx, "6. Audit Strategy", 2), p(docx, ctx.wpNotes?.a3 || "[Substantive vs combined approach per area, sampling methodology, use of analytical procedures]"),
    h(docx, "7. Team Allocation", 2),
    tbl(docx, ["Role", "Name", "Grade", "Hours"], [["Partner", ctx.partner || "", "Partner", ""], ["Manager", ctx.manager || "", "Manager", ""], ["Senior", "", "Senior", ""], ["Staff", "", "Junior", ""]]),
    h(docx, "8. Timetable", 2),
    tbl(docx, ["Milestone", "Target Date", "Status"], [["Planning meeting", "", ""], ["Interim visit", "", ""], ["Year-end visit", "", ""], ["Final visit", "", ""], ["Report clearance", "", ""], ["Signing", "", ""]]),
    p(docx, ""), p(docx, "Prepared by: " + (ctx.partner || "[Partner]")), p(docx, "Date: " + new Date().toISOString().slice(0, 10)),
  ];
  const doc = mkDoc(docx, ctx, ch);
  const blob = await docx.Packer.toBlob(doc);
  dlBlob(blob, mkName(ctx, "PLAN", "Planning_Memo"));
}

// ─── F) COMPLETION MEMO ───
export async function generateCompletionMemoDocx(ctx) {
  const docx = await loadDocx();
  const ch = [
    h(docx, "AUDIT COMPLETION MEMORANDUM"), p(docx, ctx.entityName || "[Entity]", { bold: true, size: 28 }),
    p(docx, "Year ended " + (ctx.fye || "[FYE]")), p(docx, ""),
    h(docx, "1. Summary of Findings", 2), p(docx, ctx.wpNotes?.e6 || "[Summary]"),
    h(docx, "2. Unadjusted Misstatements (ISA 450)", 2),
    tbl(docx, ["Ref", "Description", "Dr (£)", "Cr (£)", "FS Line", "Effect on Profit"], [["UM01", "", "", "", "", ""]]),
    p(docx, "Aggregate effect: £[amount]. Materiality: £" + (ctx.materiality || "TBD") + ". Conclusion: [individually and in aggregate immaterial / material]"),
    h(docx, "3. Adjusted Misstatements", 2),
    tbl(docx, ["Ref", "Description", "Dr (£)", "Cr (£)", "Adjusted"], [["AM01", "", "", "", "Yes"]]),
    h(docx, "4. Going Concern (ISA 570)", 2), p(docx, ctx.wpNotes?.a7_overall_conclusion || "[Conclusion]"),
    h(docx, "5. Subsequent Events (ISA 560)", 2), p(docx, ctx.wpNotes?.e3 || "[Events reviewed through report date]"),
    h(docx, "6. Fraud Discussion (ISA 240)", 2), p(docx, "[Document outcome of team discussion on fraud risks and any indicators identified]"),
    h(docx, "7. Significant Matters", 2), p(docx, ctx.wpNotes?.e6_matters || "[No significant matters]"),
    h(docx, "8. Quality Review Summary", 2), p(docx, "[EQCR required: Yes/No. If yes, reviewer and date. Hot review findings.]"),
    h(docx, "9. Opinion Recommendation", 2), p(docx, ctx.wpNotes?.e6_opinion || "[Unmodified opinion recommended]"),
    p(docx, ""), p(docx, "Engagement Partner: " + (ctx.partner || "[Partner]")), p(docx, "Date: " + new Date().toISOString().slice(0, 10)),
  ];
  const doc = mkDoc(docx, ctx, ch);
  const blob = await docx.Packer.toBlob(doc);
  dlBlob(blob, mkName(ctx, "COMP", "Completion_Memo"));
}

// ─── G) APPROACH PAPER ───
export async function generateApproachPaperDocx(ctx) {
  const docx = await loadDocx();
  const areas = ["Revenue", "Receivables", "Inventory", "Payables", "Cash", "Fixed Assets", "Intangibles", "Equity", "Loans", "Provisions", "Tax", "Leases", "Related Parties"];
  const ch = [
    h(docx, "AUDIT APPROACH PAPER"), p(docx, ctx.entityName || "[Entity]", { bold: true, size: 28 }),
    p(docx, "Year ended " + (ctx.fye || "[FYE]")), p(docx, ""),
    ...areas.flatMap(area => [
      h(docx, area, 2),
      tbl(docx, ["Element", "Detail"], [["Identified risks", ""], ["Planned response", ""], ["Nature of procedures", "Substantive / Combined"], ["Timing", "Interim / Final"], ["Extent (sample size)", ""], ["Assertions addressed", ""], ["Use of experts", "No / Yes — [detail]"], ["Component allocation", "N/A"]]),
    ]),
    p(docx, ""), p(docx, "Approved by: " + (ctx.partner || "[Partner]")),
  ];
  const doc = mkDoc(docx, ctx, ch);
  const blob = await docx.Packer.toBlob(doc);
  dlBlob(blob, mkName(ctx, "APPROACH", "Approach_Paper"));
}

// ─── H) CONFIRMATION LETTERS ───
export async function generateConfirmationLettersDocx(ctx) {
  const docx = await loadDocx();
  const ch = [
    h(docx, "EXTERNAL CONFIRMATION LETTERS"), p(docx, "ISA (UK) 505", { color: "666666" }), p(docx, ""),
    // Bank confirmation
    h(docx, "1. Bank Confirmation (ICAEW Standard Format)", 2),
    p(docx, "To: [Bank Name]"), p(docx, "Branch: [Branch Address]"), p(docx, ""),
    p(docx, "Dear Sir/Madam,"),
    p(docx, "In accordance with the request of our customer " + (ctx.entityName || "[Entity]") + ", we ask that you provide the following information directly to our auditors " + (ctx.firmName || "[Firm]") + " as at " + (ctx.fye || "[FYE]") + ":"),
    bullet(docx, "All accounts held in the name of the customer (current, deposit, loan, overdraft)"),
    bullet(docx, "Balances on each account as at " + (ctx.fye || "[FYE]")),
    bullet(docx, "Details of all facilities (limits, interest rates, security, covenants)"),
    bullet(docx, "Contingent liabilities (guarantees, bonds, letters of credit)"),
    bullet(docx, "Assets held as security or in safe custody"),
    p(docx, ""), p(docx, "Authorised signatory: ____________________________"),
    p(docx, "For and on behalf of " + (ctx.entityName || "[Entity]")),
    // Trade debtor
    h(docx, "2. Trade Debtor Confirmation (Positive)", 2),
    p(docx, "To: [Customer Name and Address]"), p(docx, ""),
    p(docx, "Dear Sir/Madam,"),
    p(docx, "Our auditors " + (ctx.firmName || "[Firm]") + " are carrying out the audit of our financial statements. Please confirm directly to them the balance due from you to " + (ctx.entityName || "[Entity]") + " as at " + (ctx.fye || "[FYE]") + "."),
    p(docx, "Balance per our records: £____________"), p(docx, "Balance per your records: £____________"),
    p(docx, "If the above balance is not in agreement, please provide details of differences."),
    // Trade creditor
    h(docx, "3. Trade Creditor Confirmation (Positive)", 2),
    p(docx, "To: [Supplier Name and Address]"), p(docx, ""),
    p(docx, "Dear Sir/Madam,"),
    p(docx, "Our auditors " + (ctx.firmName || "[Firm]") + " are carrying out the audit of our financial statements. Please confirm directly to them the balance due from " + (ctx.entityName || "[Entity]") + " to you as at " + (ctx.fye || "[FYE]") + "."),
    p(docx, "Balance per our records: £____________"), p(docx, "Balance per your records: £____________"),
    p(docx, "If the above balance is not in agreement, please provide details of differences including invoices, credit notes, and payments in transit."),
    p(docx, ""), p(docx, "Authorised signatory: ____________________________"),
    p(docx, "For and on behalf of " + (ctx.entityName || "[Entity]")),
    // Solicitor
    h(docx, "4. Solicitor Confirmation (ISA 505)", 2),
    p(docx, "To: [Solicitor's Name and Address]"), p(docx, ""),
    p(docx, "Dear Sirs,"),
    p(docx, "In connection with the audit of " + (ctx.entityName || "[Entity]") + " for the year ended " + (ctx.fye || "[FYE]") + ", please provide our auditors " + (ctx.firmName || "[Firm]") + " with the following information:"),
    bullet(docx, "All outstanding litigation, claims, and assessments"),
    bullet(docx, "Your assessment of the likely outcome and potential financial exposure"),
    bullet(docx, "Any other matters of which you are aware that may affect the financial statements"),
    p(docx, ""), p(docx, "Authorised signatory: ____________________________"),
    p(docx, "For and on behalf of " + (ctx.entityName || "[Entity]")),
  ];
  const doc = mkDoc(docx, ctx, ch);
  const blob = await docx.Packer.toBlob(doc);
  dlBlob(blob, mkName(ctx, "CONF", "Confirmation_Letters"));
}
