// ═══════════════════════════════════════════════════════════════
// XLSX EXPORTER — Real .xlsx generation via SheetJS
// AuditEngine v10 AURA
// ═══════════════════════════════════════════════════════════════

/**
 * Create a workbook from multiple sheets and trigger download.
 * @param {string} filename
 * @param {Array<{name:string, data:Array<Array>}>} sheets
 */
async function writeWorkbook(filename, sheets) {
  const XLSX = await import("xlsx");
  const wb = XLSX.utils.book_new();
  sheets.forEach(s => {
    const ws = XLSX.utils.aoa_to_sheet(s.data);
    // Auto-width columns based on content
    const colWidths = [];
    s.data.forEach(row => {
      row.forEach((cell, ci) => {
        const len = String(cell || "").length;
        colWidths[ci] = Math.max(colWidths[ci] || 8, Math.min(len + 2, 50));
      });
    });
    ws["!cols"] = colWidths.map(w => ({ wch: w }));
    XLSX.utils.book_append_sheet(wb, ws, s.name.slice(0, 31)); // Excel 31-char sheet name limit
  });
  const wbout = XLSX.write(wb, { bookType: "xlsx", type: "array" });
  const blob = new Blob([wbout], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  URL.revokeObjectURL(a.href);
}

/**
 * Build standard cover sheet data.
 */
function coverSheet(ctx, wp) {
  return {
    name: "Cover",
    data: [
      ["AUDIT WORKING PAPER"],
      [],
      ["Working Paper", wp.ref + " — " + wp.label],
      ["Entity", ctx.entityName || ""],
      ["FYE", ctx.fye || ""],
      ["Industry", ctx.industry || ""],
      ["Sector", ctx.sector || ""],
      ["Framework", ctx.framework || ""],
      ["Materiality", "£" + (ctx.materiality || "TBD")],
      ["Performance Materiality", "£" + (ctx.perfMateriality || "TBD")],
      ["Trivial", "£" + (ctx.trivial || "TBD")],
      ["ISA Reference", wp.isa || ""],
      [],
      ["Prepared By", ctx.signOffs?.[wp.id]?.preparedBy || ""],
      ["Reviewed By", ctx.signOffs?.[wp.id]?.reviewedBy || ""],
      ["Generated", new Date().toISOString().slice(0, 10)],
      [],
      ["Notes", ctx.wpNotes?.[wp.id] || ""],
      [],
      ["Generated by AuditEngine v10 AURA"]
    ]
  };
}

/**
 * Extract cell data for a WP prefix into rows.
 */
function extractCellData(cellData, prefix) {
  const keys = Object.keys(cellData).filter(k =>
    k.startsWith(prefix + "_") ||
    k.startsWith("fsli_" + prefix + "_") ||
    k.startsWith("sub_" + prefix + "_") ||
    k.startsWith("proc_" + prefix + "_") ||
    k.startsWith("test_" + prefix + "_") ||
    k.startsWith("cyc_" + prefix + "_")
  );
  if (!keys.length) return null;
  const rows = [["Key", "Value"]];
  keys.forEach(k => rows.push([k, cellData[k]]));
  return { name: "Cell Data", data: rows };
}

/**
 * Build a standardised filename: entityName_FYE_WPRef_YYYYMMDD.ext
 */
function buildFilename(ctx, wpRef, ext) {
  const entity = (ctx.entityName || "Entity").replace(/[^a-zA-Z0-9]/g, "_");
  const fye = (ctx.yearEnd || ctx.fye || "FYE").replace(/[^a-zA-Z0-9]/g, "");
  const ref = (wpRef || "WP").replace(/[^a-zA-Z0-9]/g, "_");
  const date = new Date().toISOString().slice(0, 10).replace(/-/g, "");
  return entity + "_" + fye + "_" + ref + "_" + date + "." + ext;
}

// ═══ EXPORT FUNCTIONS BY WP TYPE ═══

/**
 * Testing working papers (D1-D16): Cover, Procedures, Sample Grid, Results, Conclusion
 */
export async function exportTestingWP(wp, ctx) {
  const sheets = [coverSheet(ctx, wp)];

  // FSLI Lead sheet
  const fsliLines = ctx.fsliLines || [];
  if (fsliLines.length) {
    const fsliData = [["FSLI Line Item", "PY (£)", "CY (£)", "Movement (£)", "Movement %", "Ref", "Status"]];
    fsliLines.forEach((l, i) => {
      fsliData.push([
        l,
        ctx.getCell ? ctx.getCell("fsli_" + wp.id, i, 1) : "",
        ctx.getCell ? ctx.getCell("fsli_" + wp.id, i, 2) : "",
        "", "", wp.ref, ""
      ]);
    });
    sheets.push({ name: "FSLI Lead", data: fsliData });
  }

  // Procedures sheet
  const tests = [...(ctx.tests?.[wp.id] || []), ...(ctx.customTests?.[wp.id] || [])];
  if (tests.length) {
    const procData = [["Ref", "Procedure", "Assertion", "ISA", "Sample", "Result", "Exceptions", "Judgment", "Judgment Note", "Prepared", "Reviewed"]];
    tests.forEach((t, i) => {
      procData.push([wp.ref + ".S" + String(i + 1).padStart(2, "0"), t, "", wp.isa || "", "", "", "", "", "", "", ""]);
    });
    sheets.push({ name: "Procedures", data: procData });
  }

  // Sample Grid
  const sampleData = [["#", "Item Selected", "Value (£)", "Test Performed", "Result", "Exception", "Comment"]];
  for (let i = 1; i <= 25; i++) sampleData.push([i, "", "", "", "", "", ""]);
  sheets.push({ name: "Sample Grid", data: sampleData });

  // Results
  sheets.push({
    name: "Results",
    data: [
      ["Metric", "Value"],
      ["Total items tested", ""],
      ["Exceptions found", ""],
      ["Exception rate %", ""],
      ["Material exceptions", ""],
      ["Conclusion", ctx.wpNotes?.["conclusion_" + wp.id] || ""],
      ["Follow-up required", ""],
      ["Prepared by", ctx.signOffs?.[wp.id]?.preparedBy || ""],
      ["Reviewed by", ctx.signOffs?.[wp.id]?.reviewedBy || ""],
      ["Date", new Date().toISOString().slice(0, 10)]
    ]
  });

  // Conclusion
  sheets.push({
    name: "Conclusion",
    data: [
      ["Working Paper Conclusion"],
      [],
      ["Notes", ctx.wpNotes?.[wp.id] || ""],
      ["Conclusion", ctx.wpNotes?.["conclusion_" + wp.id] || ""],
    ]
  });

  // Cell data if any
  const cd = extractCellData(ctx.cellData || {}, wp.id);
  if (cd) sheets.push(cd);

  // Evidence Links
  if (ctx.procedureLinks) {
    const evData = [["Procedure Key", "Linked Evidence"]];
    Object.entries(ctx.procedureLinks).forEach(([key, ids]) => { if (ids && ids.length) evData.push([key, ids.join(", ")]); });
    if (evData.length > 1) sheets.push({ name: "Evidence Links", data: evData });
  }

  const filename = buildFilename(ctx, wp.ref, "xlsx");
  await writeWorkbook(filename, sheets);
}

/**
 * Lead schedules (C2-C8): Cover, Schedule with PY/CY/Movement
 */
export async function exportLeadSchedule(wp, ctx) {
  const sheets = [coverSheet(ctx, wp)];

  // Main schedule
  if (ctx.leadHeaders && ctx.leadRows) {
    const data = [ctx.leadHeaders];
    ctx.leadRows.forEach(row => {
      data.push(row.map(cell => {
        if (cell && typeof cell === "object" && cell.props?.children) return String(cell.props.children);
        return cell || "";
      }));
    });
    sheets.push({ name: wp.label.slice(0, 31), data });
  }

  const cd = extractCellData(ctx.cellData || {}, wp.id);
  if (cd) sheets.push(cd);

  const filename = buildFilename(ctx, wp.ref, "xlsx");
  await writeWorkbook(filename, sheets);
}

/**
 * Financial models (FM1-FM8): Cover, Input, Calculation, Output
 */
export async function exportFinancialModel(wp, ctx) {
  const sheets = [coverSheet(ctx, wp)];

  const cd = extractCellData(ctx.cellData || {}, wp.id);
  if (cd) sheets.push(cd);

  // Model-specific data passed via ctx.modelData
  if (ctx.modelData) {
    if (ctx.modelData.inputs) {
      const inputData = [["Input Parameter", "Value"]];
      Object.entries(ctx.modelData.inputs).forEach(([k, v]) => inputData.push([k, v]));
      sheets.push({ name: "Inputs", data: inputData });
    }
    if (ctx.modelData.outputs) {
      const outputData = [["Output", "Value"]];
      Object.entries(ctx.modelData.outputs).forEach(([k, v]) => outputData.push([k, v]));
      sheets.push({ name: "Outputs", data: outputData });
    }
  }

  const filename = buildFilename(ctx, wp.ref, "xlsx");
  await writeWorkbook(filename, sheets);
}

/**
 * Financial statements (FS1-FS4): Cover, Statement layout
 */
export async function exportFinancialStatement(wp, ctx) {
  const sheets = [coverSheet(ctx, wp)];

  const cd = extractCellData(ctx.cellData || {}, wp.id);
  if (cd) sheets.push(cd);

  const filename = buildFilename(ctx, wp.ref, "xlsx");
  await writeWorkbook(filename, sheets);
}

/**
 * Planning working papers (A2-A6, A8-A10): Cover, Assessment tables
 */
export async function exportPlanningWP(wp, ctx) {
  const sheets = [coverSheet(ctx, wp)];

  const cd = extractCellData(ctx.cellData || {}, wp.id);
  if (cd) sheets.push(cd);

  const filename = buildFilename(ctx, wp.ref, "xlsx");
  await writeWorkbook(filename, sheets);
}

/**
 * Risk working papers (B1-B3): Cover, Risk matrices
 */
export async function exportRiskWP(wp, ctx) {
  const sheets = [coverSheet(ctx, wp)];

  // Risk data
  if (ctx.risks) {
    const riskData = [["Ref", "Risk", "Level", "ISA", "Response"]];
    ctx.risks.forEach(r => riskData.push([r.id, r.t, r.lv, r.isa, r.rs || ""]));
    sheets.push({ name: "Risk Matrix", data: riskData });
  }

  const cd = extractCellData(ctx.cellData || {}, wp.id);
  if (cd) sheets.push(cd);

  const filename = buildFilename(ctx, wp.ref, "xlsx");
  await writeWorkbook(filename, sheets);
}

/**
 * Completion working papers (E1-E3, E5-E6, DC1): Cover, Checklists
 */
export async function exportCompletionWP(wp, ctx) {
  const sheets = [coverSheet(ctx, wp)];

  const cd = extractCellData(ctx.cellData || {}, wp.id);
  if (cd) sheets.push(cd);

  const filename = buildFilename(ctx, wp.ref, "xlsx");
  await writeWorkbook(filename, sheets);
}

/**
 * Regulatory working papers (REG1-REG4): Cover, Compliance tables
 */
export async function exportRegulatoryWP(wp, ctx) {
  const sheets = [coverSheet(ctx, wp)];

  const cd = extractCellData(ctx.cellData || {}, wp.id);
  if (cd) sheets.push(cd);

  const filename = buildFilename(ctx, wp.ref, "xlsx");
  await writeWorkbook(filename, sheets);
}

/**
 * Research working papers (RES1): Cover, Research Topics, ISA Reference, Key Findings
 */
export async function exportResearchWP(wp, ctx) {
  const sheets = [coverSheet(ctx, wp)];

  // Research topics sheet
  const topicsData = [["Topic", "ISA Reference", "Key Findings", "Relevance to Engagement", "Source", "Status"]];
  topicsData.push(["Audit methodology", wp.isa || "ISA 200-720", "", ctx.industry || "", "", ""]);
  topicsData.push(["Inherent risk factors", "ISA 315", "", "", "", ""]);
  topicsData.push(["Industry-specific risks", "ISA 315.A35", "", ctx.industry || "", "", ""]);
  topicsData.push(["Accounting standards", ctx.framework || "FRS 102", "", "", "", ""]);
  topicsData.push(["Regulatory environment", "ISA 250", "", ctx.sector || "", "", ""]);
  sheets.push({ name: "Research Topics", data: topicsData });

  // ISA cross-reference sheet
  const isaData = [["ISA Reference", "Title", "Applicability", "Key Requirements", "Notes"]];
  isaData.push(["ISA 200", "Overall Objectives", "Always", "Professional scepticism, reasonable assurance", ""]);
  isaData.push(["ISA 240", "Fraud", "Always", "Revenue recognition, management override", ""]);
  isaData.push(["ISA 250", "Laws & Regulations", "Always", "Direct and indirect compliance", ""]);
  isaData.push(["ISA 315", "Risk Assessment", "Always", "Understanding entity and environment", ""]);
  isaData.push(["ISA 330", "Responses to Risks", "Always", "Overall and specific responses", ""]);
  isaData.push(["ISA 450", "Evaluation of Misstatements", "Always", "Accumulate and evaluate", ""]);
  isaData.push(["ISA 500", "Audit Evidence", "Always", "Sufficient appropriate evidence", ""]);
  isaData.push(["ISA 520", "Analytical Procedures", "Always", "Planning and completion", ""]);
  isaData.push(["ISA 570", "Going Concern", "Always", "Assess and evaluate", ""]);
  isaData.push(["ISA 700", "Forming an Opinion", "Always", "True and fair view", ""]);
  sheets.push({ name: "ISA Cross-Reference", data: isaData });

  const cd = extractCellData(ctx.cellData || {}, wp.id);
  if (cd) sheets.push(cd);

  const filename = buildFilename(ctx, wp.ref, "xlsx");
  await writeWorkbook(filename, sheets);
}

/**
 * Chart of Accounts (COA1): Cover, GL Codes, Account Classification, TB Mapping
 */
export async function exportChartOfAccountsWP(wp, ctx) {
  const sheets = [coverSheet(ctx, wp)];

  // Chart of Accounts schedule
  const coaData = [["GL Code", "Account Name", "Account Type", "FSLI Mapping", "PY Balance (£)", "CY Balance (£)", "Movement (£)", "Notes"]];
  coaData.push(["", "", "Revenue", "", "", "", "", ""]);
  coaData.push(["", "", "Cost of Sales", "", "", "", "", ""]);
  coaData.push(["", "", "Administrative Expenses", "", "", "", "", ""]);
  coaData.push(["", "", "Fixed Assets", "", "", "", "", ""]);
  coaData.push(["", "", "Current Assets", "", "", "", "", ""]);
  coaData.push(["", "", "Current Liabilities", "", "", "", "", ""]);
  coaData.push(["", "", "Non-Current Liabilities", "", "", "", "", ""]);
  coaData.push(["", "", "Equity", "", "", "", "", ""]);
  sheets.push({ name: "Chart of Accounts", data: coaData });

  // TB Mapping sheet
  const tbData = [["GL Code", "TB Description", "Mapped FSLI", "Lead Schedule Ref", "Testing WP Ref", "Verified"]];
  for (var i = 0; i < 20; i++) tbData.push(["", "", "", "", "", ""]);
  sheets.push({ name: "TB Mapping", data: tbData });

  const cd = extractCellData(ctx.cellData || {}, wp.id);
  if (cd) sheets.push(cd);

  const filename = buildFilename(ctx, wp.ref, "xlsx");
  await writeWorkbook(filename, sheets);
}

/**
 * Standards Browser (STD1): Cover, Standards Index, Applicable Standards, Compliance Status
 */
export async function exportStandardsBrowserWP(wp, ctx) {
  const sheets = [coverSheet(ctx, wp)];

  // Framework standards index
  var fwLabel = ctx.framework || "FRS 102";
  var standardsData = [["Standard", "Section", "Title", "Applicable", "Compliance Status", "Notes"]];
  if (fwLabel.indexOf("FRS 102") >= 0) {
    standardsData.push(["FRS 102", "s2", "Concepts and Pervasive Principles", "Yes", "", ""]);
    standardsData.push(["FRS 102", "s3", "Financial Statement Presentation", "Yes", "", ""]);
    standardsData.push(["FRS 102", "s4", "Statement of Financial Position", "Yes", "", ""]);
    standardsData.push(["FRS 102", "s5", "Statement of Comprehensive Income", "Yes", "", ""]);
    standardsData.push(["FRS 102", "s6", "Statement of Changes in Equity", "Yes", "", ""]);
    standardsData.push(["FRS 102", "s7", "Statement of Cash Flows", "Yes", "", ""]);
    standardsData.push(["FRS 102", "s8", "Notes to the Financial Statements", "Yes", "", ""]);
    standardsData.push(["FRS 102", "s11", "Basic Financial Instruments", "Assess", "", ""]);
    standardsData.push(["FRS 102", "s12", "Other Financial Instruments", "Assess", "", ""]);
    standardsData.push(["FRS 102", "s13", "Inventories", "Assess", "", ""]);
    standardsData.push(["FRS 102", "s14/15", "Investments", "Assess", "", ""]);
    standardsData.push(["FRS 102", "s16", "Investment Property", "Assess", "", ""]);
    standardsData.push(["FRS 102", "s17", "Property, Plant and Equipment", "Assess", "", ""]);
    standardsData.push(["FRS 102", "s18", "Intangible Assets", "Assess", "", ""]);
    standardsData.push(["FRS 102", "s19", "Business Combinations and Goodwill", "Assess", "", ""]);
    standardsData.push(["FRS 102", "s20", "Leases", "Assess", "", ""]);
    standardsData.push(["FRS 102", "s21", "Provisions and Contingencies", "Assess", "", ""]);
    standardsData.push(["FRS 102", "s22", "Liabilities and Equity", "Yes", "", ""]);
    standardsData.push(["FRS 102", "s23", "Revenue", "Yes", "", ""]);
    standardsData.push(["FRS 102", "s26", "Share-based Payment", "Assess", "", ""]);
    standardsData.push(["FRS 102", "s27", "Impairment of Assets", "Assess", "", ""]);
    standardsData.push(["FRS 102", "s28", "Employee Benefits", "Assess", "", ""]);
    standardsData.push(["FRS 102", "s29", "Income Tax", "Assess", "", ""]);
    standardsData.push(["FRS 102", "s33", "Related Party Disclosures", "Yes", "", ""]);
  } else {
    standardsData.push(["IFRS", "IAS 1", "Presentation of Financial Statements", "Yes", "", ""]);
    standardsData.push(["IFRS", "IAS 7", "Statement of Cash Flows", "Yes", "", ""]);
    standardsData.push(["IFRS", "IAS 8", "Accounting Policies", "Yes", "", ""]);
    standardsData.push(["IFRS", "IAS 12", "Income Taxes", "Assess", "", ""]);
    standardsData.push(["IFRS", "IAS 16", "Property, Plant and Equipment", "Assess", "", ""]);
    standardsData.push(["IFRS", "IAS 19", "Employee Benefits", "Assess", "", ""]);
    standardsData.push(["IFRS", "IAS 24", "Related Party Disclosures", "Yes", "", ""]);
    standardsData.push(["IFRS", "IAS 36", "Impairment of Assets", "Assess", "", ""]);
    standardsData.push(["IFRS", "IAS 37", "Provisions and Contingencies", "Assess", "", ""]);
    standardsData.push(["IFRS", "IAS 38", "Intangible Assets", "Assess", "", ""]);
    standardsData.push(["IFRS", "IFRS 9", "Financial Instruments", "Assess", "", ""]);
    standardsData.push(["IFRS", "IFRS 15", "Revenue", "Yes", "", ""]);
    standardsData.push(["IFRS", "IFRS 16", "Leases", "Assess", "", ""]);
  }
  sheets.push({ name: "Standards Index", data: standardsData });

  // ISA compliance sheet
  var isaData = [["ISA Ref", "Title", "Key Requirement", "Addressed In WP", "Status"]];
  isaData.push(["ISA 200", "Overall Objectives", "Professional scepticism", "", ""]);
  isaData.push(["ISA 210", "Terms of Engagement", "Engagement letter", "A1", ""]);
  isaData.push(["ISA 220", "Quality Control", "Engagement performance", "E1", ""]);
  isaData.push(["ISA 230", "Documentation", "Sufficient documentation", "E6", ""]);
  isaData.push(["ISA 240", "Fraud", "Fraud risk assessment", "A6", ""]);
  isaData.push(["ISA 250", "Laws & Regulations", "Compliance assessment", "A9", ""]);
  isaData.push(["ISA 300", "Planning", "Audit strategy", "A3", ""]);
  isaData.push(["ISA 315", "Risk Assessment", "Understanding entity", "B1-B4", ""]);
  isaData.push(["ISA 320", "Materiality", "Setting materiality", "A4", ""]);
  isaData.push(["ISA 330", "Responses to Risk", "Audit procedures", "D1-D18", ""]);
  isaData.push(["ISA 450", "Misstatements", "Summary of adjustments", "E5", ""]);
  isaData.push(["ISA 500", "Audit Evidence", "Sufficient appropriate", "D1-D18", ""]);
  isaData.push(["ISA 505", "External Confirmations", "Confirmation process", "CONF1", ""]);
  isaData.push(["ISA 520", "Analytical Procedures", "Planning and completion", "A8/E2", ""]);
  isaData.push(["ISA 540", "Accounting Estimates", "Estimation uncertainty", "D7", ""]);
  isaData.push(["ISA 550", "Related Parties", "RP identification", "D15", ""]);
  isaData.push(["ISA 560", "Subsequent Events", "Post year-end review", "E3", ""]);
  isaData.push(["ISA 570", "Going Concern", "GC assessment", "A7", ""]);
  isaData.push(["ISA 580", "Written Representations", "Management reps", "E4", ""]);
  isaData.push(["ISA 700", "Audit Report", "Forming opinion", "F2", ""]);
  sheets.push({ name: "ISA Compliance", data: isaData });

  const cd = extractCellData(ctx.cellData || {}, wp.id);
  if (cd) sheets.push(cd);

  const filename = buildFilename(ctx, wp.ref, "xlsx");
  await writeWorkbook(filename, sheets);
}

/**
 * Reporting working papers (F3, F4): Cover, Findings, Recommendations
 */
export async function exportReportingWP(wp, ctx) {
  const sheets = [coverSheet(ctx, wp)];

  // Findings sheet
  var findingsData = [["Ref", "Finding", "Risk Rating", "ISA Reference", "Impact", "Recommendation", "Management Response", "Status"]];
  for (var i = 1; i <= 10; i++) findingsData.push([wp.ref + "." + i, "", "", "", "", "", "", ""]);
  sheets.push({ name: "Findings", data: findingsData });

  // Summary sheet
  sheets.push({
    name: "Summary",
    data: [
      ["Reporting Summary"],
      [],
      ["Entity", ctx.entityName || ""],
      ["FYE", ctx.yearEnd || ctx.fye || ""],
      ["Prepared For", wp.id === "f4" ? "Audit Committee" : "Management"],
      ["Framework", ctx.framework || ""],
      [],
      ["Total Findings", ""],
      ["High Risk", ""],
      ["Medium Risk", ""],
      ["Low Risk", ""],
      [],
      ["Conclusion", ctx.wpNotes?.[wp.id] || ""],
      ["Prepared By", ctx.signOffs?.[wp.id]?.preparedBy || ""],
      ["Reviewed By", ctx.signOffs?.[wp.id]?.reviewedBy || ""],
    ]
  });

  const cd = extractCellData(ctx.cellData || {}, wp.id);
  if (cd) sheets.push(cd);

  const filename = buildFilename(ctx, wp.ref, "xlsx");
  await writeWorkbook(filename, sheets);
}

/**
 * Audit Trail Map (Z1): Cover, WP Index, Cross-References, Completion Status
 */
export async function exportTrailWP(wp, ctx) {
  const sheets = [coverSheet(ctx, wp)];

  // WP Index — list all WPs and their status
  var wpIndex = [["WP Ref", "Title", "Type", "ISA", "Prepared By", "Reviewed By", "Status"]];
  if (ctx.WPS) {
    ctx.WPS.forEach(function(w) {
      if (w.type === "separator") return;
      var so = ctx.signOffs?.[w.id] || {};
      var status = so.preparedBy && so.reviewedBy ? "Complete" : so.preparedBy ? "Prepared" : "Not Started";
      wpIndex.push([w.ref, w.label, w.type, w.isa || "", so.preparedBy || "", so.reviewedBy || "", status]);
    });
  }
  sheets.push({ name: "WP Index", data: wpIndex });

  // Cross-reference map
  var xrefData = [["From WP", "To WP", "Nature of Link", "Notes"]];
  xrefData.push(["A3", "B1-B4", "Strategy drives risk assessment", ""]);
  xrefData.push(["B1-B4", "D1-D18", "Risks drive testing programmes", ""]);
  xrefData.push(["C1-C8", "D1-D18", "Lead schedules underpin testing", ""]);
  xrefData.push(["D1-D18", "E5", "Exceptions feed adjustments summary", ""]);
  xrefData.push(["E1-E6", "F1-F2", "Completion informs reporting", ""]);
  sheets.push({ name: "Cross-References", data: xrefData });

  const cd = extractCellData(ctx.cellData || {}, wp.id);
  if (cd) sheets.push(cd);

  const filename = buildFilename(ctx, wp.ref, "xlsx");
  await writeWorkbook(filename, sheets);
}

/**
 * Generic xlsx export for any WP not covered by specific exporters.
 */
export async function exportGenericWP(wp, ctx) {
  const sheets = [coverSheet(ctx, wp)];

  const cd = extractCellData(ctx.cellData || {}, wp.id);
  if (cd) sheets.push(cd);

  const filename = buildFilename(ctx, wp.ref, "xlsx");
  await writeWorkbook(filename, sheets);
}
